### ISSUE TITLE
First Boot GUI does not display audio device by default

### ISSUE THREAD

**Issue by kmoore134** [trueos/trueos-utils-qt5#1]
When running first-boot GUI, the audio devices appear in the drop-down, but appears empty by default. (Until you select something)

**Comment by kmoore134** [comment]
Over to ken!

**Comment by beanpole135** [comment]
Fixed!
bbcbf4acdb751ea83fc58626262257fadeffc073

I also updated the "Test sound" button to use the internal QMultimedia framework instead of calling out to mplayer.
