### ISSUE TITLE
Date is ambiguous in Update Manager

### ISSUE THREAD

**Issue by dlavigne** [trueos/trueos-utils-qt5#4]
See attached screenshot for an example. Depending upon where you live in the world, the last check either occurred on Aug 11 or Nov 8. Specifically stating the month name would make this clear.
![update1](https://cloud.githubusercontent.com/assets/486100/17598921/bfa3905e-5fca-11e6-93e4-24015e236427.png)

**Comment by kmoore134** [comment]
This issue was moved to trueos/sysadm-ui-qt#5
