### ISSUE TITLE
Installation GUI: more clarity around nondestructive installation (reuse of an existing pool); 'Cancel' is not the best word, and so on

### ISSUE THREAD

**Issue by kmoore134** [trueos/trueos-utils-qt5#7]
_From @grahamperrin on August 27, 2016 7:15_

The routine for this recently added feature includes the following modal dialogue: 

> **Install to existing zpool?**
> The following existing zpool(s) have been found. 
> Do you wish to install fresh into a new BootEnvironment? (This will preserve your $HOME data and other datasets)
> [menu of pools]
> [[OK]] [Cancel]

**Consistency**

Re https://github.com/trueos/sysadm-ui-qt/issues/15 and https://www.illumos.org/issues/5659#note-4 it's proper to use the word _pool_ (not zpool) to describe a pool. And/but see below …

**Plain English/language**

Designed from the ground up for [**ease of use**](https://web.archive.org/web/20160827064235/https://www.trueos.org/downloads/) so let's consider use cases such as –

- a newcomer to PC-BSD making first use of an installer for TrueOS Desktop
- a newcomer to TrueOS Desktop reinstalling the OS, or using a more recent installer

– in such cases, phrases such as _pool_, _tank_, _tank1_, _BootEnvironment_ (one word), _$HOME_ and _datasets_ may be quite alien to the user. 

Generally, the dialogue may be confusing. 

A question in the title bar (to which a Yes/No answer will be appropriate), then a mention of something that follows, then what follows (a different question requiring a Yes/No answer) is not what was mentioned, then an explanation in parentheses, then something in a non-labelled menu, then instead of Yes/No there's OK/Cancel and the untrained user might reasonably expect Cancel to cancel the installation – or cancel the proceedings – but Cancel causes installation to proceed to a different screen. 

The modal dialogue approach is OK for early alpha/beta testing the new nondestructive approach to installation :+1: but I reckon that in addition to improved wording, it will be more user-friendly to **integrate _the question_ and _the menu of pools_ into the underlying interface** (with Back, Next and so on). 

I'll sit on this for a while, maybe play ball with some wording ideas in IRC and https://gitter.im/trueos/Lobby before adding something more constructive to this issue :)

_Copied from original issue: trueos/trueos-core#42_

**Comment by wblock** [comment]
On Sun, 28 Aug 2016, Kris Moore wrote:

> 
> From @grahamperrin on August 27, 2016 7:15
> 
> The routine for this recently added feature includes the following modal dialogue:
>
>       Install to existing zpool?
>       The following existing zpool(s) have been found.

Please don't pluralize words with parentheses.  It is an affront to 
decency.  Either write the code to append an "s" if the number is not 
one, or just remove the parentheses in recognition that a plural usually 
works for any number.

"The following" can also go.  It is meant to notify the reader that 
first we will be talking about something else, then the important thing 
will be following.  Here, it immediately precedes the thing and is 
pointless.  So please, just make this simpler:

   These ZFS pools have been found:

     tank
     tank1
     tanks

   The installation can go to one of these existing pools, or to a new
   boot environment, preserving $HOME data and other datasets.

   [Install to existing pool] [Install to new boot environment]

(Note: don't make the user try to figure out what Okay and Cancel map to 
when the choices are not Go or Stop.  Just use those choices in the 
buttons.)

And if no existing pools are found, don't show this message.

**Comment by grahamperrin** [comment]
Thanks @kmoore134 and I should add, this enhancement request arose partly from a comment in IRC – 

>> … there was a geli option for trueos?  :( I missed it

– to which I replied: 

> the traditional 'advanced' dialogue is an option only if you click 'Cancel' in one of the dialogues. Which reminds me, there should be better wording in that dialogue

**Comment by wblock** [comment]
Come to think of it, there is an even better way to present this.  The choices can all be part of the same list:

```
Please choose a destination:

Install to:

[New boot environment (preserves $HOME and other datasets)]
ZFS Pools:
[tank]
[tank1]
[tanks]

[Accept]   [Go back]
```
The four choices in this example are active items in a list box.  The first one is the recommended choice so is already selected when the dialog opens.  The user only needs to make one choice instead of two.
