### ISSUE TITLE
Inconsistant wording on final screen of installer.

### ISSUE THREAD

**Issue by xzovy** [trueos/trueos-utils-qt5#8]
On the last screen of the installer, it tells the user to "Click Finish to reboot." However, there is no "Finish" button, only "Save Config to USB", "Abort" and "Exit". I think standardizing on "Finish" would be best since it implies completion, while "Exit" and "Abort" could be confused.

**Comment by kmoore134** [comment]
This issue was moved to trueos/trueos-core#77
